# Generated by Django 4.1 on 2022-11-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flujo",
            fields=[
                ("id_flujo", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_flujo", models.CharField(max_length=100)),
                ("fecha_creacion", models.DateField()),
                ("fecha_primera_ejecucion", models.DateField()),
                ("fecha_ultima_ejecucion", models.DateField()),
                ("descripcion", models.CharField(max_length=200)),
            ],
            options={"db_table": "flujo", "managed": False,},
        ),
        migrations.CreateModel(
            name="TipoFlujo",
            fields=[
                (
                    "id_tipo_flujo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("tipo", models.CharField(max_length=200)),
            ],
            options={"db_table": "tipo_flujo", "managed": False,},
        ),
    ]
