# Generated by Django 4.1 on 2022-12-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flujos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoFlujo",
            fields=[
                (
                    "id_estado_flujo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("estado_flujo", models.CharField(max_length=50)),
            ],
            options={"db_table": "estado_flujo", "managed": False,},
        ),
    ]
