# Generated by Django 4.1 on 2022-09-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ciudad",
            fields=[
                ("id_ciudad", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_ciudad", models.CharField(max_length=250)),
            ],
            options={"db_table": "ciudad", "managed": False,},
        ),
        migrations.CreateModel(
            name="Comuna",
            fields=[
                ("id_comuna", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_comuna", models.CharField(max_length=100)),
            ],
            options={"db_table": "comuna", "managed": False,},
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id_direccion",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nombre_calle", models.CharField(max_length=250)),
                ("numero_casa", models.BigIntegerField()),
            ],
            options={"db_table": "direccion", "managed": False,},
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("id_persona", models.BigAutoField(primary_key=True, serialize=False)),
                ("rut_persona", models.CharField(max_length=10)),
                ("nombre_persona", models.CharField(max_length=30)),
                ("apellido_paterno_persona", models.CharField(max_length=30)),
                ("apellido_materno_persona", models.CharField(max_length=30)),
            ],
            options={"db_table": "persona", "managed": False,},
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id_region", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_region", models.CharField(max_length=250)),
            ],
            options={"db_table": "region", "managed": False,},
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("id_rol", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
            ],
            options={"db_table": "rol", "managed": False,},
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_usuario", models.CharField(max_length=50)),
                ("password_usuario", models.CharField(max_length=50)),
            ],
            options={"db_table": "usuario", "managed": False,},
        ),
    ]
