# Generated by Django 4.1 on 2022-09-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarea",
            fields=[
                ("id_tarea", models.BigAutoField(primary_key=True, serialize=False)),
                ("titulo_tarea", models.CharField(max_length=50)),
                ("desc_tarea", models.CharField(max_length=500)),
                ("fecha_inicio", models.DateField()),
                ("fecha_termino", models.DateField()),
                ("etiqueta", models.CharField(max_length=50)),
                ("porc_cumplimiento", models.BigIntegerField()),
                ("estado_tarea", models.CharField(max_length=50)),
            ],
            options={"db_table": "tarea", "managed": False,},
        ),
        migrations.CreateModel(
            name="TareaPersona",
            fields=[
                (
                    "id_tarea_persona",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
            options={"db_table": "tarea_persona", "managed": False,},
        ),
    ]
