# Generated by Django 4.1 on 2022-10-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_tarea_tareapersona"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estado",
            fields=[
                ("id_estado", models.BigAutoField(primary_key=True, serialize=False)),
                ("estado", models.CharField(max_length=50)),
            ],
            options={"db_table": "estado", "managed": False,},
        ),
    ]
