# Generated by Django 4.1 on 2022-10-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permisos",
            fields=[
                ("id_permiso", models.BigAutoField(primary_key=True, serialize=False)),
                ("tipo_permiso", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=500)),
            ],
            options={"db_table": "permisos", "managed": False,},
        ),
    ]
