# Generated by Django 4.1 on 2022-10-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_permisos"),
    ]

    operations = [
        migrations.DeleteModel(name="Permisos",),
    ]
