# Generated by Django 4.1 on 2022-12-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_responsable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id_departamento",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("departamento", models.CharField(max_length=150)),
            ],
            options={"db_table": "departamento", "managed": False,},
        ),
        migrations.CreateModel(
            name="Gerencia",
            fields=[
                ("id_gerencia", models.BigAutoField(primary_key=True, serialize=False)),
                ("gerencia", models.CharField(max_length=150)),
            ],
            options={"db_table": "gerencia", "managed": False,},
        ),
        migrations.CreateModel(
            name="Subgerencia",
            fields=[
                (
                    "id_subgerencia",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("subgerencia", models.CharField(max_length=150)),
            ],
            options={"db_table": "subgerencia", "managed": False,},
        ),
    ]
