# Generated by Django 4.1 on 2022-12-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_departamento_gerencia_subgerencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportarProblema",
            fields=[
                ("id_reporte", models.BigAutoField(primary_key=True, serialize=False)),
                ("descripcion_reporte", models.CharField(max_length=250)),
                ("fecha_generacion", models.DateField()),
            ],
            options={"db_table": "reportar_problema", "managed": False,},
        ),
    ]
