# Generated by Django 4.1 on 2022-09-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Usuario",),
    ]
